// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIUWJosOVuinouqq75me04zm9GCOch6hI',
    appId: '1:234134538766:web:e73ab5d6c6683a97e40a5f',
    messagingSenderId: '234134538766',
    projectId: 'quanlythuvien-f7b6c',
    authDomain: 'quanlythuvien-f7b6c.firebaseapp.com',
    storageBucket: 'quanlythuvien-f7b6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCloP2UqUE5AeMKV8SsvFezJIrmbbDAcwM',
    appId: '1:234134538766:android:872303013bf4db9ae40a5f',
    messagingSenderId: '234134538766',
    projectId: 'quanlythuvien-f7b6c',
    storageBucket: 'quanlythuvien-f7b6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvW_S2sHVXaa9Yps6L8hskeWE5_MMts6Y',
    appId: '1:234134538766:ios:b9464dfb1e355c63e40a5f',
    messagingSenderId: '234134538766',
    projectId: 'quanlythuvien-f7b6c',
    storageBucket: 'quanlythuvien-f7b6c.firebasestorage.app',
    iosBundleId: 'com.example.quanlythuvienApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvW_S2sHVXaa9Yps6L8hskeWE5_MMts6Y',
    appId: '1:234134538766:ios:b9464dfb1e355c63e40a5f',
    messagingSenderId: '234134538766',
    projectId: 'quanlythuvien-f7b6c',
    storageBucket: 'quanlythuvien-f7b6c.firebasestorage.app',
    iosBundleId: 'com.example.quanlythuvienApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIUWJosOVuinouqq75me04zm9GCOch6hI',
    appId: '1:234134538766:web:9b207918da3fdaa6e40a5f',
    messagingSenderId: '234134538766',
    projectId: 'quanlythuvien-f7b6c',
    authDomain: 'quanlythuvien-f7b6c.firebaseapp.com',
    storageBucket: 'quanlythuvien-f7b6c.firebasestorage.app',
  );
}
